parameters:
    chameleon_system_core.cache.cache_less_files: true
    chameleon_system_core.cache.allow: true
    chameleon_system_core.debug.debug_last_order: false
    chameleon_system_core.cache.memcache_activate: true
    chameleon_system_core.cache.memcache_use_fallback: false
    chameleon_system_core.cache.include_cache_delete_trace_info: false
