<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    AppBundle\AppBundle::class => ['all' => true],
    ChameleonSystem\AmazonPaymentBundle\ChameleonSystemAmazonPaymentBundle::class => ['all' => true],
    ChameleonSystem\AtomicLockBundle\ChameleonSystemAtomicLockBundle::class => ['all' => true],
    ChameleonSystem\AutoclassesBundle\ChameleonSystemAutoclassesBundle::class => ['all' => true],
    ChameleonSystem\ChameleonShopThemeBundle\ChameleonSystemChameleonShopThemeBundle::class => ['all' => true],
    ChameleonSystem\CmsActionPluginBundle\ChameleonSystemCmsActionPluginBundle::class => ['all' => true],
    ChameleonSystem\CmsCacheBundle\ChameleonSystemCmsCacheBundle::class => ['all' => true],
    ChameleonSystem\CmsCaptchaBundle\ChameleonSystemCmsCaptchaBundle::class => ['all' => true],
    ChameleonSystem\CmsChangeLogBundle\ChameleonSystemCmsChangeLogBundle::class => ['all' => true],
    ChameleonSystem\CmsClassManagerBundle\ChameleonSystemCmsClassManagerBundle::class => ['all' => true],
    ChameleonSystem\CmsCoreLogBundle\ChameleonSystemCmsCoreLogBundle::class => ['all' => true],
    ChameleonSystem\CmsCounterBundle\ChameleonSystemCmsCounterBundle::class => ['all' => true],
    ChameleonSystem\CmsFileManagerBundle\ChameleonSystemCmsFileManagerBundle::class => ['all' => true],
    ChameleonSystem\CmsInterfaceManagerBundle\ChameleonSystemCmsInterfaceManagerBundle::class => ['all' => true],
    ChameleonSystem\CmsNavigationBundle\ChameleonSystemCmsNavigationBundle::class => ['all' => true],
    ChameleonSystem\CmsNavigationPkgShopBundle\ChameleonSystemCmsNavigationPkgShopBundle::class => ['all' => true],
    ChameleonSystem\CmsResultCacheBundle\ChameleonSystemCmsResultCacheBundle::class => ['all' => true],
    ChameleonSystem\CmsRoutingBundle\ChameleonSystemCmsRoutingBundle::class => ['all' => true],
    ChameleonSystem\CmsStringUtilitiesBundle\ChameleonSystemCmsStringUtilitiesBundle::class => ['all' => true],
    ChameleonSystem\CmsTextBlockBundle\ChameleonSystemCmsTextBlockBundle::class => ['all' => true],
    ChameleonSystem\CmsTextFieldBundle\ChameleonSystemCmsTextFieldBundle::class => ['all' => true],
    ChameleonSystem\CommentBundle\ChameleonSystemCommentBundle::class => ['all' => true],
    ChameleonSystem\CookieConsentBundle\ChameleonSystemCookieConsentBundle::class => ['all' => true],
    ChameleonSystem\CoreBundle\ChameleonSystemCoreBundle::class => ['all' => true],
    ChameleonSystem\CoreValidatorConstraintsBundle\ChameleonSystemCoreValidatorConstraintsBundle::class => ['all' => true],
    ChameleonSystem\Csv2SqlBundle\ChameleonSystemCsv2SqlBundle::class => ['all' => true],
    ChameleonSystem\DatabaseMigrationBundle\ChameleonSystemDatabaseMigrationBundle::class => ['all' => true],
    ChameleonSystem\DebugBundle\ChameleonSystemDebugBundle::class => ['dev' => true, 'test' => true],
    ChameleonSystem\DistributionBundle\ChameleonSystemDistributionBundle::class => ['dev' => true, 'test' => true],
    ChameleonSystem\ExternalTrackerBundle\ChameleonSystemExternalTrackerBundle::class => ['all' => true],
    ChameleonSystem\ExternalTrackerGoogleAnalyticsBundle\ChameleonSystemExternalTrackerGoogleAnalyticsBundle::class => ['all' => true],
    ChameleonSystem\ExtranetBundle\ChameleonSystemExtranetBundle::class => ['all' => true],
    ChameleonSystem\ExtranetRegistrationGuestBundle\ChameleonSystemExtranetRegistrationGuestBundle::class => ['all' => true],
    ChameleonSystem\GenericTableExportBundle\ChameleonSystemGenericTableExportBundle::class => ['all' => true],
    ChameleonSystem\ImageHotspotBundle\ChameleonSystemImageHotspotBundle::class => ['all' => true],
    ChameleonSystem\JavaScriptMinificationBundle\ChameleonSystemJavaScriptMinificationBundle::class => ['all' => true],
    ChameleonSystem\MediaManagerBundle\ChameleonSystemMediaManagerBundle::class => ['all' => true],
    ChameleonSystem\MinifierJsJshrinkBundle\ChameleonSystemMinifierJsJshrinkBundle::class => ['all' => true],
    ChameleonSystem\MultiModuleBundle\ChameleonSystemMultiModuleBundle::class => ['all' => true],
    ChameleonSystem\NewsletterBundle\ChameleonSystemNewsletterBundle::class => ['all' => true],
    ChameleonSystem\PkgCoreBundle\ChameleonSystemPkgCoreBundle::class => ['all' => true],
    ChameleonSystem\RevisionManagementBundle\ChameleonSystemRevisionManagementBundle::class => ['all' => true],
    ChameleonSystem\SanityCheckBundle\ChameleonSystemSanityCheckBundle::class => ['all' => true],
    ChameleonSystem\SanityCheckChameleonBundle\ChameleonSystemSanityCheckChameleonBundle::class => ['all' => true],
    ChameleonSystem\SearchBundle\ChameleonSystemSearchBundle::class => ['all' => true],
    ChameleonSystem\ShopAffiliateBundle\ChameleonSystemShopAffiliateBundle::class => ['all' => true],
    ChameleonSystem\ShopArticleDetailPagingBundle\ChameleonSystemShopArticleDetailPagingBundle::class => ['all' => true],
    ChameleonSystem\ShopArticlePreorderBundle\ChameleonSystemShopArticlePreorderBundle::class => ['all' => true],
    ChameleonSystem\ShopArticleReviewBundle\ChameleonSystemShopArticleReviewBundle::class => ['all' => true],
    ChameleonSystem\ShopBundle\ChameleonSystemShopBundle::class => ['all' => true],
    ChameleonSystem\ShopCurrencyBundle\ChameleonSystemShopCurrencyBundle::class => ['all' => true],
    ChameleonSystem\ShopDhlPackstationBundle\ChameleonSystemShopDhlPackstationBundle::class => ['all' => true],
    ChameleonSystem\ShopListFilterBundle\ChameleonSystemShopListFilterBundle::class => ['all' => true],
    ChameleonSystem\ShopNewsletterSignupWithOrderBundle\ChameleonSystemShopNewsletterSignupWithOrderBundle::class => ['all' => true],
    ChameleonSystem\ShopOrderStatusBundle\ChameleonSystemShopOrderStatusBundle::class => ['all' => true],
    ChameleonSystem\ShopOrderViaPhoneBundle\ChameleonSystemShopOrderViaPhoneBundle::class => ['all' => true],
    ChameleonSystem\ShopPaymentHandlerSofortueberweisungBundle\ChameleonSystemShopPaymentHandlerSofortueberweisungBundle::class => ['all' => true],
    ChameleonSystem\ShopPaymentIPNBundle\ChameleonSystemShopPaymentIPNBundle::class => ['all' => true],
    ChameleonSystem\ShopPaymentTransactionBundle\ChameleonSystemShopPaymentTransactionBundle::class => ['all' => true],
    ChameleonSystem\ShopPrimaryNavigationBundle\ChameleonSystemShopPrimaryNavigationBundle::class => ['all' => true],
    ChameleonSystem\ShopProductExportBundle\ChameleonSystemShopProductExportBundle::class => ['all' => true],
    ChameleonSystem\ShopRatingServiceBundle\ChameleonSystemShopRatingServiceBundle::class => ['all' => true],
    ChameleonSystem\ShopWishlistBundle\ChameleonSystemShopWishlistBundle::class => ['all' => true],
    ChameleonSystem\SnippetRendererBundle\ChameleonSystemSnippetRendererBundle::class => ['all' => true],
    ChameleonSystem\TrackViewsBundle\ChameleonSystemTrackViewsBundle::class => ['all' => true],
    ChameleonSystem\TwigDebugBundle\ChameleonSystemTwigDebugBundle::class => ['dev' => true, 'test' => true],
    ChameleonSystem\UpdateCounterMigrationBundle\ChameleonSystemUpdateCounterMigrationBundle::class => ['all' => true],
    ChameleonSystem\UrlAliasBundle\ChameleonSystemUrlAliasBundle::class => ['all' => true],
    ChameleonSystem\ViewRendererBundle\ChameleonSystemViewRendererBundle::class => ['all' => true],
    Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
];
