name: Run Codeception test cases

on: [push]

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
#          ini-values: post_max_size=256M, max_execution_time=180
          ini-values: max_execution_time=3333
#          coverage: xdebug
#          tools: php-cs-fixer, phpunit

      - name: Install dependencies
        run:  composer install

      - name: Run chromedriver
        run:  nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &

      - name: Run test cases
        run:  php vendor/bin/codecept run acceptance -c codeception.yml
